name: geopandas_env
channels:
  - conda-forge # Channel utama untuk package sains & geo
  - defaults
dependencies:
  - python=3.9        # Pin Python version
  - pip               # Pastikan pip terinstal di conda env
  - gdal              # Explicitly install GDAL (C library) via conda-forge
  - geopandas=0.10.2  # Versi stabil yang tadi kita coba
  - fiona=1.8.21      # Pastikan kompatibel dengan geopandas 0.10.2
  - pyproj=3.2.1      # Pastikan kompatibel
  - shapely=1.8.0     # Pastikan kompatibel
  - rtree=0.9.7       # Pastikan kompatibel
  - pandas=2.2.3
  - numpy=2.1.3
  - scikit-learn=1.7.0
  - folium=0.20.0
  - joblib=1.2.0
  # Tambahan: Pastikan build tools dasar tersedia di lingkungan conda
  - mamba-lib         # Bagian dari mambaforge
  - build-essential   # Ini akan coba diinstal dari conda-forge jika ada
  - gcc_linux-64      # Kompiler GCC dari conda-forge
  # List library yang hanya ada di pip, masukkan di bawah 'pip:'
  - pip:
    - streamlit==1.46.0
    - streamlit-folium==0.25.0
