[theme]
# Warna utama untuk elemen interaktif
primaryColor="#0068c9"

# Warna latar belakang utama aplikasi
backgroundColor="#FFFFFF"

# Warna latar belakang untuk elemen seperti sidebar dan widget
secondaryBackgroundColor="#F0F2F6"

# Warna teks utama
textColor="#000000"

# Font yang digunakan
font="sans serif"