[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[logger]
level = "info"

[global]
# Tentukan versi Python yang lebih stabil untuk kompatibilitas geopandas
python_version = "3.9" # <--- TAMBAHKAN BARIS INI!

# Force Streamlit to build the environment with specific system packages needed by geopandas
packages = ["build-essential", "libgdal-dev", "libspatialindex-dev", "gdal-bin"]

[install]
runOn = "startup"
build_command = "pip install -r requirements.txt"
