[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"

[logger]
level = "info"

[global]
# Pastikan versi Python sama dengan di environment.yml
python_version = "3.9"

# AKTIFKAN PENGGUNAAN CONDA (mambaforge)
using_conda = true # <--- UBAH/TAMBAHKAN BARIS INI!

[install]
# Jika using_conda=true, Streamlit akan otomatis mencari environment.yml
# build_command tidak perlu didefinisikan lagi secara spesifik untuk instalasi pip,
# karena pip packages di environment.yml akan diinstal otomatis setelah conda env.
runOn = "startup"
# build_command = "pip install -r requirements.txt" # Baris ini bisa dihapus atau dikomentari
